// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: operator-openshift
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2020-07-11
:page-description: Explore how to deploy microservices using the Open Liberty Operator on Red Hat OpenShift
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'okd']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Deploying Java microservices using the Open Liberty Operator on Red Hat OpenShift
:page-seo-description: A getting started tutorial with examples on how to deploy Java microservices using the Kubernetes Operator for Open Liberty on a Red Hat OpenShift cluster.
:guide-author: Open Liberty
= Deploying microservices using the Open Liberty Operator on OpenShift

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy microservices by using the Open Liberty Operator on Red Hat OpenShift.

== What you'll learn 

You will learn how to use the Open Liberty Operator to deploy two microservices in Open Liberty containers to Red Hat OpenShift.

https://www.openshift.com/[OpenShift^] is a Kubernetes-based platform with added functions. It streamlines the DevOps
process by providing an intuitive development pipeline. It also provides integration with multiple tools to make the
deployment and management of cloud applications easier.

The https://github.com/OpenLiberty/open-liberty-operator[Open Liberty Operator^] provides a method of deploying and
managing Open Liberty applications on OpenShift or OKD, which is the community distribution of OpenShift, clusters. The Open
Liberty Operator watches Open Liberty resources and creates various Kubernetes resources, including `Deployments`,
`Services`, and `Routes`, depending on the configurations. The Operator then continuously compares the current state of
the resources and the desired state of application deployment and reconciles them when necessary. To learn more
about OpenShift Operators, check out this https://www.openshift.com/learn/topics/operators[Operators tech topic article^].

You will deploy two microservices, `system` and `inventory`, to an OpenShift cluster using the Open Liberty Operator.
The `system` and `inventory` applications will communicate with a Kafka container that you will deploy directly from
Docker Hub. To learn more about the reactive Java application that is used in this guide and how it works, check out the
https://openliberty.io/guides/microprofile-reactive-messaging.html[Creating reactive Java microservices^] guide.

== Additional prerequisites

Before you begin, you need the following tools:

- *OpenShift cluster*: You need admin access and control over the OpenShift cluster that you deploy your application to.
There are various types of deployments, including free versions for you to try. Check out the official
https://www.openshift.com/try[Red Hat website^] for all the options. The simplest option is to gain temporary free access to
OpenShift Online, Red Hat's cloud offering. This guide was written and tested with OpenShift Container Platform 4.3. Ensure
you are using version 4.x because the Dockerfiles used in this guide use the `--chown` flag, which is incompatible with
older versions of Docker.

- *Docker*: You need a containerization software for building containers. You will use Docker in this guide. For
installation instructions, refer to the official https://docs.docker.com/install/[Docker documentation^].

*Make sure to run all commands in this guide from inside your OpenShift cluster.*

// Getting Started block

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

== Installing the Open Liberty Operator

Ensure you are logged in to your cluster as an administrator.

Before you install any resources, you need a project on your OpenShift cluster. Create a project named `guide` by
running the following command:

[role='command']
```
oc new-project guide
```

To install the Open Liberty Operator, navigate to the web console, then to *Operators > OperatorHub* on the sidebar.
Search for and install the *Open Liberty Operator*.

Run the following command to view all the supported API resources available through the Open Liberty Operator:

[role='command']
```
oc api-resources --api-group=openliberty.io
```

You see the following output, which shows the custom resource definitions (CRDs) that are installed by the Operator for use:

[role='no_copy']
```
NAME                      SHORTNAMES         APIGROUP         NAMESPACED   KIND
openlibertyapplications   olapp,olapps       openliberty.io   true         OpenLibertyApplication
openlibertydumps          oldump,oldumps     openliberty.io   true         OpenLibertyDump
openlibertytraces         oltrace,oltraces   openliberty.io   true         OpenLibertyTrace
```

The Open Liberty Operator introduces new
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[CRDs^],
including the `OpenLibertyApplication`. The `OpenLibertyApplication` CRD defines a set of configurations for
deploying an Open Liberty-based application, including the application image, number of instances, and storage settings.

You will be using the `OpenLibertyApplication` resource in the upcoming sections.

== Deploying the system and inventory applications to OpenShift

//File 0
build.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/build.yaml[]
----

//File 1
deploy.yaml
[source, yaml, linenums, role='code_column hide_tags=replicas']
----
include::finish/deploy.yaml[]
----

To deploy the Open Liberty `system` and `inventory` applications, you must first package the applications and build the Docker
images. Then, you need to push the images to the internal OpenShift registry and deploy the images by using the Open Liberty Operator.

=== Packaging the applications

Navigate to the `start` directory and run the following commands to package the `system` and `inventory`
applications:

[role='command']
```
mvn -pl models clean install
mvn clean package
```

=== Building and pushing the images

Create a build template to configure how to build your images.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `build.yaml` template file.#
`build.yaml`
----

The [hotspot file=0]`build.yaml` template includes two objects. The [hotspot=imageStream file=0]`image stream` object provides an abstraction
from the image in the image registry, allowing you to reference and tag the image. The image registry that is used is
the integrated internal OpenShift Container Registry.

The [hotspot=buildConfig file=0]`build configuration` object defines a single
build definition and any triggers that kickstart the build. The [hotspot=source file=0]`source` spec defines the build input. In this case,
the build inputs are your [hotspot=binary file=0]`binary` (local) files, which are streamed to OpenShift for the build. The template specifies
a [hotspot=docker file=0]`Docker` strategy build, which invokes the `docker build` command, and creates a runnable application image
from the build input. The template is parameterized with the [hotspot=appname file=0]`APP_NAME` parameter so that the same
template can be used to create the objects for the `system` and `inventory` applications separately.

include::{common-includes}/ol-kernel-docker-pull.adoc[]

Run the following commands to create the objects for the `system` and `inventory` applications:

[role='command']
```
oc process -f build.yaml -p APP_NAME=system | oc create -f -
oc process -f build.yaml -p APP_NAME=inventory | oc create -f -
```

Next, run the following commands to view the newly created image streams and build configurations for each application:

[role='command']
```
oc get all -l name=system
oc get all -l name=inventory
```

You see the following resources:

[role='no_copy']
```
NAME                                                TYPE     FROM     LATEST
buildconfig.build.openshift.io/system-buildconfig   Docker   Binary   0

NAME                                                IMAGE REPOSITORY                                                            TAGS           UPDATED
imagestream.image.openshift.io/system-imagestream   image-registry.openshift-image-registry.svc:5000/guide/system-imagestream   1.0-SNAPSHOT   2 days ago

...

NAME                                                   TYPE     FROM     LATEST
buildconfig.build.openshift.io/inventory-buildconfig   Docker   Binary   2

NAME                                                   IMAGE REPOSITORY                                                               TAGS           UPDATED
imagestream.image.openshift.io/inventory-imagestream   image-registry.openshift-image-registry.svc:5000/guide/inventory-imagestream   1.0-SNAPSHOT   2 days ago
```

Ensure that you are in the `start` directory and trigger the builds by running the following commands:

[role='command']
```
oc start-build system-buildconfig --from-dir=system/.
oc start-build inventory-buildconfig --from-dir=inventory/.
```

The local `system` and `inventory` directories are uploaded to OpenShift to be built into the Docker images. Run the
following command to list the builds and track their status:

[role='command']
```
oc get builds
```

You see the following output:

[role='no_copy']
```
NAME                      TYPE     FROM             STATUS     STARTED
system-buildconfig-1      Docker   Binary@f24cb58   Running    45 seconds ago
inventory-buildconfig-1   Docker   Binary@f24cb58   Running    13 seconds ago
```

You may need to wait some time until the build is complete. To check whether the build is complete, run the following
commands to view the build logs until the `Push successful` message appears:

[role='command']
```
oc logs build/system-buildconfig-1
oc logs build/inventory-buildconfig-1
```

Run the following command to view the image streams:

[role='command']
```
oc get imagestreams
```

Run the following commands to get more details on the newly pushed images within the streams:

[role='command']
```
oc describe imagestream/system-imagestream
oc describe imagestream/inventory-imagestream
```

This example partially shows the `system-imagestream` output:

[role='no_copy']
```
Name:                     system-imagestream
Namespace:                guide
Created:                  2 minutes ago
Labels:                   name=system
Annotations:              <none>
Image Repository:         image-registry.openshift-image-registry.svc:5000/guide/system-imagestream
Image Lookup:             local=false
Unique Images:            1
Tags:                     1

...
```

You'll get a similar output for the `inventory-imagestream`.

Now you're ready to deploy the images.

=== Deploying the images

You can configure the specifics of the Open Liberty Operator-controlled deployment with a YAML configuration file.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `deploy.yaml` configuration file.#
`deploy.yaml`
----

The [hotspot file=1]`deploy.yaml` file is configured to deploy two [hotspot=olapp1 hotspot=olapp2 file=1]`OpenLibertyApplication`
resources, [hotspot=system file=1]`system` and [hotspot=inventory file=1]`inventory`, which will be controlled by
the Open Liberty Operator.

The [hotspot=sysImage file=1]`applicationImage` parameter value is the only necessary parameter, and can be set by using the
`<project-name>/<image-stream-name>[:tag]` format. The parameter can also point to an image hosted on an external registry, such as
Docker Hub. The [hotspot=system file=1]`system` application is configured to use the
[hotspot=sysImage file=1]`image` created from the earlier build. By default, the operator automatically redeploys
applications when it detects a new image was pushed into the `ImageStream`. If you are using an external image, you can define
the pull policy by using a `pullPolicy` configuration parameter. The
[hotspot=systemEnv file=1]`env` parameter is used to specify environment variables that are passed to the container at runtime.
The necessary environment variables to communicate with [hotspot=systemEnv file=1]`Kafka` are provided.

The [hotspot=inventory file=1]`inventory` application is configured similarly to the [hotspot=system file=1]`system`
application. Additionally, the `inventory` application includes the [hotspot=service file=1]`service` and
[hotspot=expose file=1]`expose` parameters. The [hotspot=servicePort file=1]`service.port` parameter specifies which port
is exposed by the container, allowing the application to be accessed from outside the container. To access the application
from outside of the cluster, it must be exposed, by setting the [hotspot=expose file=1]`expose` parameter to `true`.
Exposing the application lets the Operator automatically create and configure routes for external access to your application.

Run the following command to deploy the `system` and `inventory` applications with the previously explained configurations:

[role='command']
```
oc apply -f deploy.yaml
```

Next, run the following command to view your newly created `OpenLibertyApplication` resources:

[role='command']
```
oc get OpenLibertyApplications
```

You can also substitute `OpenLibertyApplications` with the short form `olapps`.

Run the following commands to view details of your applications:

[role='command']
```
oc describe olapps/system
oc describe olapps/inventory
```

This example partially shows the `olapps/system` output:

[role='no_copy']
```
Name:         system
Namespace:    guide
Labels:       app.kubernetes.io/part-of=system
              name=system
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"openliberty.io/v1beta1","kind":"OpenLibertyApplication","metadata":{"annotations":{},"labels":{"name":"system"},"name":"sys...
API Version:  openliberty.io/v1beta1
Kind:         OpenLibertyApplication

...
```

You'll get a similar output for `olapps/inventory`.

The `system` and `inventory` applications are not yet functional because they depend on Kafka, which is deployed in the
next section.

== Deploying the Kafka service to OpenShift

Apache Kafka is the messaging broker that's used in this application. The image required to deploy the application is available
and can be pulled and deployed directly from Docker Hub. Kafka relies on Zookeeper to manage Kafka configuration
and clusters, and the Zookeeper image is also on Docker Hub.

To deploy Zookeeper, run the following command:

[role='command']
```
oc new-app bitnami/zookeeper:3 \
  -l name=kafka \
  -e ALLOW_ANONYMOUS_LOGIN=yes
```

The `bitnami/zookeeper:3` parameter indicates which `zookeeper` Docker Hub image to pull and deploy.
The `-e [key]=[value]` flag provides an environment variable to the newly created application.

To deploy Kafka, run the following command:

[role='command']
```
oc new-app bitnami/kafka:2 \
  -l name=kafka \
  -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e ALLOW_PLAINTEXT_LISTENER=yes \
  -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
```

Run the following command to display all the deployed resources that are associated with the Zookeeper and Kafka applications:

[role='command']
```
oc get all -l name=kafka
```

You see the following output:

[role='no_copy']
```
NAME                    READY   STATUS    RESTARTS   AGE
pod/kafka-1-l9jht       1/1     Running   0          7s
pod/zookeeper-1-2hq6f   1/1     Running   0          23s

NAME                                DESIRED   CURRENT   READY   AGE
replicationcontroller/kafka-1       1         1         1       10s
replicationcontroller/zookeeper-1   1         1         1       26s

NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
service/kafka       ClusterIP   172.30.189.177   <none>        9092/TCP                              11s
service/zookeeper   ClusterIP   172.30.193.179   <none>        2181/TCP,2888/TCP,3888/TCP,8080/TCP   28s

NAME                                           REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/kafka       1          1         1         config,image(kafka:2)
deploymentconfig.apps.openshift.io/zookeeper   1          1         1         config,image(zookeeper:3)

NAME                                       IMAGE REPOSITORY                                                   TAGS   UPDATED
imagestream.image.openshift.io/kafka       image-registry.openshift-image-registry.svc:5000/guide/kafka       2      10 seconds ago
imagestream.image.openshift.io/zookeeper   image-registry.openshift-image-registry.svc:5000/guide/zookeeper   3      27 seconds ago
```

Give the cluster a few minutes for all applications to start and connect with one another.

== Accessing the inventory application

To access the exposed `inventory` application, run the following command and make note of the `HOST`:

[role='command']
```
oc get routes
```

You see an output similar to:

[role='no_copy']
```
NAME        HOST/PORT                                    PATH   SERVICES    PORT       TERMINATION   WILDCARD
inventory   inventory-guide.apps.lights.os.fyre.ibm.com         inventory   9085-tcp                 None
```


Visit the `inventory` application by going to the following URL. Make sure to substitute the appropriate `HOST`:
`http://[HOST]/inventory/systems`

For example, `inventory-guide.apps.lights.os.fyre.ibm.com` is the `HOST` in the
`\http://inventory-guide.apps.lights.os.fyre.ibm.com/inventory/systems` URL.

You see a JSON response similar to the following example, but your JSON response might not be formatted. The sample output
was formatted for readability:

[role='no_copy']
```
[
    {
        "hostname": "system-7cbc47455c-664wh",
        "systemLoad": 1.15
    }
]
```

== Scaling up the system application

//File 0
deploy.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/deploy.yaml[]
----

The `inventory` application displays the `hostname` and `systemLoad` of all `system` applications that are publishing
messages to the Kafka broker. Since only one `system` pod is running, there is only one element in the `inventory`.
Scaling applications up is easy with Operators. Simply update the `deploy.yaml` file with the `replica: n` parameter,
where `n` is the number of instances that you want.

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `deploy.yaml` configuration file.#
`deploy.yaml`
----
[role="edit_command_text"]
Add the [hotspot=replicas file=0]`replicas` parameter to the `system` configuration.

Run the following command to update the `system` resource:

[role='command']
```
oc apply -f deploy.yaml
```

You see the following output:

[role='no_copy']
```
openlibertyapplication.openliberty.io/system configured
openlibertyapplication.openliberty.io/inventory unchanged
```

Notice that only the `system` resource was updated because there was a change in its specification. The `inventory`
resource was left unchanged.

Wait a few minutes, then run the following command to see the newly scaled up `system` pods:

[role='command']
```
oc get pods
```

Revisit the `inventory` application and you now see three elements:

[role='no_copy']
```
[
    {
        "hostname": "system-5bb7b86fd5-b5plz",
        "systemLoad": 2.73
    },
    {
        "hostname": "system-5bb7b86fd5-fkd5j",
        "systemLoad": 2.95
    },
    {
        "hostname": "system-5bb7b86fd5-pgcbf",
        "systemLoad": 2.73
    }
]
```

== Tearing down the environment

When you no longer need your project, switch to another project and delete the project `guide` by running the following command:

[role='command']
```
oc delete project guide
```

This command deletes all the applications and resources.

== Great work! You're done!

You just deployed two microservices running in Open Liberty to OpenShift using the Open Liberty Operator.

== Related Links

// Multipane
include::{common-includes}/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
