// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: operators-openshift
:page-layout: guide-multipane
:page-duration: 45 minutes 
:page-releasedate: 2019-09-11
:page-description: Explore how to deploy microservices using the Open Liberty Operator on Red Hat OpenShift
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'okd']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Deploying Java microservices using the Open Liberty Operator on Red Hat OpenShift
:page-seo-description: A getting started tutorial with examples on how to deploy Java microservices using the Open Liberty Operator on an OpenShift cluster.
:guide-author: Open Liberty
= Deploying microservices using the Open Liberty Operator on OpenShift

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy microservices using the Open Liberty Operator on Red Hat OpenShift.

== What you'll learn 

[Brief intro to OpenShift + the importance of cloud infrastructures]
[Explanation of Operators and their use cases / how they’re beneficial over standard deployment processes]
[Brief summary of the guide, what the user will be walked through, the structure of the application]

== Additional prerequisites

Before you begin, the following additional tools are needed:

- *OpenShift cluster:* You need admin access and control over the OpenShift cluster you deploy your application to.
There are various types of clusters and deployments, and this guide uses OpenShift Container Platform 4.3.

- *Docker:* You need a containerization software for building containers. You will use Docker in this guide. For
installation instructions, refer to the official https://docs.docker.com/install/[Docker documentation^].

// Getting Started block

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

== Installing the Open Liberty Operator

Before installing any resources, you need a project on your OpenShift cluster. Create a new project named `guide` by
running the following command:

[role='command']
```
oc new-project guide
```

The Open Liberty Operator can be installed on an OpenShift through the CLI or through the web console.

*Installing through the CLI*

To install the Open Liberty Operator through the CLI, follow the instructions from the
https://github.com/OpenLiberty/open-liberty-operator#operator-installation[official GitHub repository^].

*Installing through the web console*

To install the Open Liberty Operator through the web console, navigate to the sidebar `Operators > OperatorHub`, and
search and install the `Open Liberty Operator`.

[add a snippet getting the project resources and showcasing the operator deployments]

== Deploying the Kafka service to OpenShift

Apache Kafka is the messaging broker used in this application. The image required to deploy the application is available
and can be pulled and deployed directly from Docker Hub.

To deploy Zookeeper, run the following command:

[role='command']
```
oc new-app bitnami/zookeeper:3 \
  -e ALLOW_ANONYMOUS_LOGIN=yes
```

The `bitnami/zookeeper:3` parameter indicates the `zookeeper` DockerHub image to pull and deploy.
The `-e [key]=[value]` flag provides an environment variable to the new app.

To deploy Kafka, run the following command:

[role='command']
```
oc new-app bitnami/kafka:2 \
  -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e ALLOW_PLAINTEXT_LISTENER=yes \
  -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
```

Run the following to display all the deployed resources associated with the Zookeeper and Kafka applications:

[role='command']
```
oc get all
```

== Deploying the system and inventory applications to OpenShift

To deploy the Open Liberty `system` and `inventory` applications, you need to package the applications, build the Docker
images, push them to the internal OpenShift registry, then deploy the images using the Open Liberty Operator.

=== Packaging the applications

Ensure that you are in the `start` directory, then run the following commands to package the `system` and `inventory`
applications:

[role='command']
```
mvn -pl models clean install
mvn clean package
```

=== Building the images

Take a look at the (hotspot)`build.yaml` template which includes two objects. The (hotspot)`image stream` object provides an easy way to
access the image that will be pushed to the container registry. The (hotspot)`build configuration` object defines the build
strategy to be used to build your application into an image. Notice that the (hotspot)`APP_NAME` is parameterized so that the same
template can be used to create the objects for the `system` and `inventory` applications separately.

Run the following commands to create the objects for the `system` and `inventory` applications:

[role='command']
```
oc process -f build.yaml -p APP_NAME=system | oc create -f -
oc process -f build.yaml -p APP_NAME=inventory | oc create -f -
```

Run the following commands to view the newly created image streams and build configurations:

[role='command']
```
oc get imagestreams
oc get buildconfigs
```

Ensure that you are in the `start` directory and trigger the builds by running the following commands:

[role='command']
```
oc start-build system-buildconfig --from-dir=system/.
oc start-build inventory-buildconfig --from-dir=inventory/.
```

The source directories will be uploaded to OpenShift to be built into the Docker images. Run the following command to
list the builds and track their status:

[role='command']
```
oc get builds
```

Run the following commands to view the build logs:

[role='command']
```
oc logs build/system-buildconfig-1
oc logs build/inventory-buildconfig-1
```

Once you see the `Push successful` message, run the following command to view the image streams:

[role='command']
```
oc get imagestreams
```

Run the following to get more details on the newly pushed images within the streams:

[role='command']
```
oc describe imagestream/inventory-imagestream
```

You can now deploy the images.

=== Deploying the images

Take a look at the (hotspot)`deploy.yaml` file, which is configured to deploy two `OpenLibertyApplication`
resources which will be controlled by the Open Liberty Operator. (Add some more explanations about the file
including port mapping, exposing services through routes, environment variables)

Run the following command to deploy the `system` and `inventory` applications:

[role='command']
```
oc apply -f deploy.yaml
```

== Accessing the inventory application

To access the `inventory` application, run the following command and make note of the `HOST`:

[role='command']
```
oc get routes
```

Then access the `inventory` application by visiting the following URL, ensure that you substitute the appropriate `HOST`:

- http://[HOST]/inventory/systems

== Scaling up the system application

The `inventory` application displays the `hostname` and `systemLoad` of all `system` applications that are publishing
messages to the Kafka broker. Since there is only one running `system` pod, there is only one element in the `inventory`.
Scaling applications up is easy with Operators, simply update the `deploy.yaml` file with the `replica: n` specification
(add an update file hotspot)

Run the following command to update the resources:

[role='command']
```
oc apply -f deploy.yaml
```

You see the following output:

[role='no_copy']
```
openlibertyapplication.openliberty.io/system created
openlibertyapplication.openliberty.io/inventory unchanged
```

Notice that only the `system` resource was updated since there was a change in its specification, and that the `inventory`
resource was left unchanged.

Run the following command to see the newly scaled up `system` pods:

[role='command']
```
oc get pods
```

Revisit the `inventory` application and you now see five elements.

== Great work! You're done!

You just deployed two microservices running in Open Liberty to OpenShift using the Open Liberty Operator.

// Multipane
include::{common-includes}/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
